#!/bin/bash
if readlink /proc/$$/exe | grep -qs "dash"; then
	echo "EXECUTE COM ( BASH ) ... SH NAO E SUPORTADO"
	exit 1
fi

if [[ "$EUID" -ne 0 ]]; then
	echo -e "\033[01;31m DESCULPE E NECESSARIO EXECUTAR ESSE SCRIPT COM ROOT"
	exit 2
fi

if [[ ! -e /dev/net/tun ]]; then
	echo "The TUN device is not available
POR FAVOR .. ATIVE O TUN NO CLOUD PARA USAR ESTA INSTALAÇAO"
	exit 3
fi

if grep -qs "CentOS release 5" "/etc/redhat-release"; then
	echo "CentOS 5 e anteriores nao sao suportados"
	exit 4
fi
if [[ -e /etc/debian_version ]]; then
	OS=debian
	GROUPNAME=nogroup
	RCLOCAL='/etc/rc.local'
elif [[ -e /etc/centos-release || -e /etc/redhat-release ]]; then
	OS=centos
	GROUPNAME=nobody
	RCLOCAL='/etc/rc.d/rc.local'
else
	echo "Looks like you aren't running this installer on Debian, Ubuntu or CentOS"
	exit 5
fi
echo -e "\033[01;31m "
read -p "DESEJA INICIAR INSTALAÇAO DO OPENVPN-SOLO? (s|n): " solo
if [ "$solo" = "s" ]; then
clear
rm /bin/ovpn/ &>/dev/null
wget -O /bin/ovpn -o /dev/null https://raw.githubusercontent.com/fenixtm/OVPN-SOLO/master/ovpn
chmod +x /bin/ovpn
clear
sleep 1
echo -e "\033[01;32m INICIANDO....."
sleep 1
ovpn
fi
if [ "$solo" = "n" ]; then
clear
echo -e "\033[01;31m ABORTADO....."
sleep 2
clear
fi
if [ "$sono" != "s" ]; then
clear
echo -e "\033[01;31m ABORTADO....."
sleep 2
clear
fi
